name: Next.js CD
on:
  push:
    branches: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd
            
            echo "Check Node.js"
            if ! command -v node &> /dev/null; then
            echo "Install Node.js"
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            fi
            
            echo "Check PM2"
            if ! command -v pm2 &> /dev/null; then
            echo "Install PM2"
            sudo npm install -g pm2
            fi
            
            git fetch origin
            git checkout deploy || git checkout -b deploy origin/deploy
            git pull origin deploy
            
            npm install
  
            npm run build

            if pm2 list | grep -q "next-app"; then
            pm2 reload next-app
            else
            pm2 start npm --name "next-app" -- start
            fi
            pm2 save

