name: Next.js CD
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Node.js & PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd

            echo "Check Node.js"
            if ! command -v node &> /dev/null; then
            echo "Install Node.js"
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            fi
            
            echo "Check PM2"
            if ! command -v pm2 &> /dev/null; then
            echo "Install PM2"
            sudo npm install -g pm2
            fi

      - name: Update repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd
            
            git fetch origin
            git checkout main || git checkout -b main origin/main
            git pull origin main

      - name: Install deps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd
            
            npm i

      - name: Building app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd
            
            rm -rf .next
            npm run build

      - name: Start PM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ci-cd
            
            if pm2 list | grep -q "ci-cd"; then
            pm2 reload ci-cd
            else
            pm2 start npm --name "ci-cd" -- start
            fi
            pm2 save
