name: Next.js CI/CD

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Next install
        run: NODE_OPTIONS="--max-old-space-size=1024" npm i next --verbose
      - name: React & React DOM install
        run: NODE_OPTIONS="--max-old-space-size=1024" npm i react react-dom --verbose
      - name: TailwindCSS install
        run: NODE_OPTIONS="--max-old-space-size=1024" npm i -D tailwindcss @tailwindcss/postcss --verbose
      - name: TypeScript install
        run: NODE_OPTIONS="--max-old-space-size=1024" npm i -D typescript @types/node @types/react @types/react-dom --verbose
      - name: ESLint install
        run: NODE_OPTIONS="--max-old-space-size=1024" npm i -D eslint eslint-config-next @eslint/eslintrc --verbose
      - run: npm run build
      - run: |
          if pm2 list | grep -q "next-app"; then
            pm2 reload next-app
          else
            pm2 start npm --name "next-app" -- start
          fi
      - run: pm2 save
