name: Next.js CI/CD

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i --no-fund --no-audit --verbose
      - run: npm run build
      - run: |
          if pm2 list | grep -q "next-app"; then
            pm2 reload next-app
          else
            pm2 start npm --name "next-app" -- start
          fi
      - run: pm2 save
